-- MySQL Script generated by MySQL Workbench
-- 02/21/18 05:32:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nyblecraft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nyblecraft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nyblecraft` DEFAULT CHARACTER SET utf8 ;
USE `nyblecraft` ;

-- -----------------------------------------------------
-- Table `nyblecraft`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyblecraft`.`user` (
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  `pdf` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`firstName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
